# created by YoungShame

import asyncio
from .. import loader, utils
from asyncio import sleep

from .. import loader, utils

@loader.tds
class LOvesMod(loader.Module):
	"""LOves"""
	strings = {'name': 'LOves'}
	@loader.owner
	async def lovescmd(self, message):
		await utils.answer(message, 'Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '    Я  Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '   Я   Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '  Я    Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я     Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я      Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я      Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я      Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я      Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я      Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я      Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я     Т ебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я    Т  ебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я   Т   ебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я  Т    ебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Т     ебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Т    е бя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Т   е  бя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Т  е   бя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Т е    бя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Те     бя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Те    б я Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Те   б  я Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Те  б   я Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Те б    я Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Теб     я Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Теб    я  Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Теб   я   Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Теб  я    Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Теб я     Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя      Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя      Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя      Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя      Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя      Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя      Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя     Л юблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя    Л  юблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя   Л   юблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя  Л    юблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Л     юблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Л    ю блю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Л   ю  блю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Л  ю   блю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Л ю    блю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Лю     блю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Лю    б лю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Лю   б  лю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Лю  б   лю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Лю б    лю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люб     лю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люб    л ю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люб   л  ю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люб  л   ю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люб л    ю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Любл     ю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Любл    ю ❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Любл   ю  ❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Любл  ю   ❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Любл ю    ❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю     ❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю    ❤️ ️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю   ❤️  ️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю  ❤️   ️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю ❤️    ️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️     ️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️    ️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️   ️ ')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️  ️  ')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️ ️   ')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️    ')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '️Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '❤️Я Тебя Люблю')
		await asyncio.sleep(1)
		await utils.answer(message, 'ю❤️Я Тебя Любл')
		await asyncio.sleep(1)
		await utils.answer(message, 'лю❤️Я Тебя Люб')
		await asyncio.sleep(1)
		await utils.answer(message, 'блю❤️Я Тебя Лю')
		await asyncio.sleep(1)
		await utils.answer(message, 'юблю❤️Я Тебя Л')
		await asyncio.sleep(1)
		await utils.answer(message, 'Люблю❤️Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, 'Люблю❤️Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, 'я Люблю❤️Я Теб')
		await asyncio.sleep(1)
		await utils.answer(message, 'бя Люблю❤️Я Те')
		await asyncio.sleep(1)
		await utils.answer(message, 'ебя Люблю❤️Я Т')
		await asyncio.sleep(1)
		await utils.answer(message, 'Тебя Люблю❤️Я')
		await asyncio.sleep(1)
		await utils.answer(message, 'Тебя Люблю❤️Я')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '️Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '❤️Я Тебя Люблю')
		await asyncio.sleep(1)
		await utils.answer(message, 'ю❤️Я Тебя Любл')
		await asyncio.sleep(1)
		await utils.answer(message, 'лю❤️Я Тебя Люб')
		await asyncio.sleep(1)
		await utils.answer(message, 'блю❤️Я Тебя Лю')
		await asyncio.sleep(1)
		await utils.answer(message, 'юблю❤️Я Тебя Л')
		await asyncio.sleep(1)
		await utils.answer(message, 'Люблю❤️Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, 'Люблю❤️Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, 'я Люблю❤️Я Теб')
		await asyncio.sleep(1)
		await utils.answer(message, 'бя Люблю❤️Я Те')
		await asyncio.sleep(1)
		await utils.answer(message, 'ебя Люблю❤️Я Т')
		await asyncio.sleep(1)
		await utils.answer(message, 'Тебя Люблю❤️Я')
		await asyncio.sleep(1)
		await utils.answer(message, 'Тебя Люблю❤️Я')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '️Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '❤️Я Тебя Люблю')
		await asyncio.sleep(1)
		await utils.answer(message, 'ю❤️Я Тебя Любл')
		await asyncio.sleep(1)
		await utils.answer(message, 'лю❤️Я Тебя Люб')
		await asyncio.sleep(1)
		await utils.answer(message, 'блю❤️Я Тебя Лю')
		await asyncio.sleep(1)
		await utils.answer(message, 'юблю❤️Я Тебя Л')
		await asyncio.sleep(1)
		await utils.answer(message, 'Люблю❤️Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, 'Люблю❤️Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, 'я Люблю❤️Я Теб')
		await asyncio.sleep(1)
		await utils.answer(message, 'бя Люблю❤️Я Те')
		await asyncio.sleep(1)
		await utils.answer(message, 'ебя Люблю❤️Я Т')
		await asyncio.sleep(1)
		await utils.answer(message, 'Тебя Люблю❤️Я')
		await asyncio.sleep(1)
		await utils.answer(message, 'Тебя Люблю❤️Я')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '  Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '   Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '    Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '     Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '      Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '       Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '        Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '         Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '          Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '         Я Тебя   Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '        Я Тебя     Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '       Я Тебя       Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '      Я Тебя         Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '     Я Тебя           Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '    Я Тебя             Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '   Я Тебя               Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '  Я Тебя                 Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя                   Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя                     Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, 'Я Тебя                   Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '  Я Тебя                 Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '   Я Тебя               Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '    Я Тебя             Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '     Я Тебя           Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '      Я Тебя         Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '       Я Тебя       Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '        Я Тебя     Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '         Я Тебя   Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '          Я Тебя Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '           Я ТебяЛюблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '            Я ТебЛюблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '             Я ТеЛюблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '              Я ТЛюблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '               Я Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '                ЯЛюблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '                 Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '                Люблю❤️')
		await asyncio.sleep(1)
		await utils.answer(message, '               Люблю❤️я')
		await asyncio.sleep(1)
		await utils.answer(message, '              Люблю❤️бя')
		await asyncio.sleep(1)
		await utils.answer(message, '             Люблю❤️ебя')
		await asyncio.sleep(1)
		await utils.answer(message, '            Люблю❤️Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '           Люблю❤️ Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '          Люблю❤️Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '         Люблю❤️  Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '        Люблю❤️    Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '       Люблю❤️      Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '      Люблю❤️        Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '     Люблю❤️          Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '    Люблю❤️            Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '   Люблю❤️              Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '  Люблю❤️                Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, 'Люблю❤️                  Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, 'Люблю❤️                    Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, 'Люблю❤️                  Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '  Люблю❤️                Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '   Люблю❤️              Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '    Люблю❤️            Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '     Люблю❤️          Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '      Люблю❤️        Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '       Люблю❤️      Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '        Люблю❤️    Я Тебя')
		await asyncio.sleep(1)
		await utils.answer(message, '         Люблю❤️  Я Тебя')
